apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: mariadb
  namespace: mysql
spec:
  selector:
    matchLabels:
      app: mariadb
  serviceName: "mariadb"
  replicas: 3
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
      - name: init-config
        command: ['/bin/bash', '/etc/mysql/conf.d/init.sh']
        env:
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: rootpw
        - name: DATADIR
          value: /var/lib/mysql
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
        - name: conf
          mountPath: /etc/mysql/conf.d
        - name: initdb
          mountPath: /docker-entrypoint-initdb.d
        image: mariadb:10.2.10@sha256:e5d38bf55611af632fad0674b2b0219dae5797845da322df78aabdfbf71ec45a
      containers:
      - name: mariadb
        image: mariadb:10.2.10@sha256:e5d38bf55611af632fad0674b2b0219dae5797845da322df78aabdfbf71ec45a
        ports:
        - containerPort: 3306
          name: mysql
        - containerPort: 4444
          name: sst
        - containerPort: 4567
          name: replication
        - containerPort: 4567
          protocol: UDP
          name: replicationudp
        - containerPort: 4568
          name: ist
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: rootpw
        - name: MYSQL_INITDB_SKIP_TZINFO
          value: "yes"
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -ec
            - >-
              mysql
              -uroot
              -p$MYSQL_ROOT_PASSWORD
              -e "SHOW STATUS LIKE 'wsrep%';"
          initialDelaySeconds: 30
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
        - name: conf
          mountPath: /etc/mysql/conf.d
        - name: initdb
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: conf
        secret:
          secretName: conf-d
      - name: initdb
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: mysql-data
      resources:
        requests:
          storage: 2Gi
