apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: mariadb
  namespace: mysql
spec:
  serviceName: "mariadb"
  replicas: 3
  template:
    metadata:
      labels:
        app: mariadb
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
        pod.alpha.kubernetes.io/init-containers: '[
        ]'
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.1
        ports:
        - containerPort: 3306
          name: mysql
        - containerPort: 4444
          name: sst
        - containerPort: 4567
          name: replication
        - containerPort: 4567
          protocol: UDP
          name: replicationudp
        - containerPort: 4568
          name: ist
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: todo-get-from-secret
          #valueFrom:
          #  secretKeyRef:
          #    name: postgres
          #    key: rootpw
        command: ['sh','-c','exec tail -f /dev/null']
        # mysql_install_db --user=mysql --datadir=/var/lib/mysql
        # gosu mysql mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --wsrep-new-cluster
        # gosu mysql mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --wsrep_cluster_address=gcomm://mariadb-0.mariadb
        args:
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
        - --wsrep-new-cluster
        - --wsrep_cluster_address=gcomm://mariadb-0.mariadb
        volumeMounts:
        - name: datadir
          mountPath: /var/lib/mysql
        - name: conf
          mountPath: /etc/mysql/conf.d
        - name: initdb
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: conf
        emptyDir: {}
      - name: initdb
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: datadir
      namespace: mysql
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Mi
